### ISSUE TITLE
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Kind(UnexpectedEof))', src/core/database.rs:67:47

### ISSUE THREAD

**Issue by abubakari3bugaru** [MaarifaMaarifa/series-troxide#1]
I got this error when installing the release binary to my linux machine.
I extract the tar file and run `./series-troxide`

I had an early version of this software and 

Here's the command info when running that command:

2023-07-21T16:19:31.553596Z  INFO series_troxide: starting 'series-troxide'
2023-07-21T16:19:31.553703Z  INFO series_troxide::core::settings_config: loading config file at: '/home/arbpure/.config/series-troxide/config.toml'
MESA-INTEL: warning: Haswell Vulkan support is incomplete
2023-07-21T16:19:31.944783Z  INFO series_troxide::core::database: opening database
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Kind(UnexpectedEof))', src/core/database.rs:67:47
note: run with `RUST_BACKTRACE=1` environment variable to display a [backtrace[](url)](url)

What can I do to run the program?

**Comment by MaarifaMaarifa** [comment]
You might be using an old version of the database data which had a breaking change around 2 weeks. To fix that head over to your $HOME/.local/share/series-troxide and remove the series-troxide-db folder. This will make series-troxide create a fresh database data when you open it again.
