### ISSUE TITLE
Unable to import trakt shows with some unknown information

### ISSUE THREAD

**Issue by MaarifaMaarifa** [MaarifaMaarifa/series-troxide#101]
I was finally able to connect with Trakt.  I went to import and get this error, "trakt api error:trakt api error when deserializing json: unexpected '  "year":null,'    any ideas?

_Originally posted by @jeff363b in https://github.com/MaarifaMaarifa/series-troxide/issues/77#issuecomment-1847158317_

**Comment by MaarifaMaarifa** [comment]
It appears that some of the trakt shows miss their premiere year. Since the program expects this information to be available, it fails to deserialize the received show jsons with a missing premiere year field.

**Comment by MaarifaMaarifa** [comment]
I'm about to release another version with the patches applied so that such shows should not cause this problem anymore.

**Comment by MaarifaMaarifa** [comment]
I have already made a new [release](https://github.com/MaarifaMaarifa/series-troxide/releases/tag/v0.4.2). You can try it out and tell me how it goes.

**Comment by jeff363b** [comment]
It seems to work for the "year", but now it is the "IMDB".....I am guessing that any field with "null" is going to kick back.  I was able to view the windows version, but not the docker version yet (need to figure how to update on that device).

**Comment by MaarifaMaarifa** [comment]
Seems like the external ids (i.e imdb, tvdb) for a trakt show json can also be null which surprisingly trakt API docs did not mention. Let me patch this too.

**Comment by MaarifaMaarifa** [comment]
I have already made the program handle trakt shows with no external ids. The program will now skip any shows with no IMDB or TVDB when importing trakt shows as the program will not be able to map these shows to their TvMaze ID.

**Comment by MaarifaMaarifa** [comment]
Feel free to reopen this issue if similar problems occur during Trakt shows import.

**Comment by jeff363b** [comment]
I have tried out the new version and it does not give me any more errors but the import hangs up at about 80%. I have canceled out and tried it numerous times and it seemed to hang up at around 75 to 90%. Not sure what the bottleneck is but it won’t complete. Just a heads up

**Comment by MaarifaMaarifa** [comment]
> I have tried out the new version and it does not give me any more errors but the import hangs up at about 80%. I have canceled out and tried it numerous times and it seemed to hang up at around 75 to 90%. Not sure what the bottleneck is but it won’t complete. Just a heads up

I'll take a close look at it and provide feedback

**Comment by jeff363b** [comment]
If it is any help, the import worked on the container version for synology.  It would hang up on the Windows version of the app.

**Comment by MaarifaMaarifa** [comment]
> If it is any help, the import worked on the container version for synology.  It would hang up on the Windows version of the app.
> 
> Now that it is all imported, it is taking a very long time to show up in the app.  The "swirling" icon in the Watchlist and "My Shows" tab keeps going around and around for a long time.  it is still swirling.  Not sure if there is a hangup there too....Hope this is all helping...

How many shows were imported from Trakt?

**Comment by jeff363b** [comment]
405 were initially attempted.  About 8 got rejected due to null data, I believe (no big deal on them as they are over anyways).

**Comment by MaarifaMaarifa** [comment]
> 405 were initially attempted. About 8 got rejected due to null data, I believe (no big deal on them as they are over anyways).

Alright, looks like the program struggles with a large import. The freeze when importing from Trakt is due to sending alot of requests to TvMaze (So as to map trakt shows IDs with TvMaze's) and not properly handling the situation when the rate limit is exceeded when using the TvMaze API which is highly likely to occur with a large import. I'll get this fixed at some point by making the program back off for a few seconds when rate limit is reached, at an expense of a slightly slower import.

> Now that it is all imported, it is taking a very long time to show up in the app. The "swirling" icon in the Watchlist and "My Shows" tab keeps going around and around for a long time. it is still swirling. Not sure if there is a hangup there too....Hope this is all helping...

This is still a rate limit problem. When the Watchlist and My Shows Tabs load after an import, the program tries to request the shows items (images, episodes etc) for the first time which with a large import can make the program hit the rate limit. The good thing is that the program caches all of these obtained information to the filesystem meaning that you can quit the program and open it again and the caching process will continue where it left off if the program loads for a long time (you can check the logs to see if caching is running or freezing). 

All of these problems will be resolved when i implement proper handling of the rate limit. Hopefully the fixes might land on the next version v0.5.0
