### ISSUE TITLE
FYI: Run this in docker

### ISSUE THREAD

**Issue by toelke** [MaarifaMaarifa/series-troxide#2]
```dockerfile
FROM rust AS builder
RUN apt update && apt -y install libgtk-3-dev libatk1.0-dev
RUN cargo install series-troxide
RUN mkdir /libs; ldd /usr/local/cargo/bin/series-troxide | grep '=>' | awk '{ print $3; }' | xargs -I_ -n 1 cp _ /libs

FROM toelke158/docker-vnc
RUN echo "#!/bin/bash\n/series-troxide" > /home/vncuser/.xsession
COPY --from=builder /usr/local/cargo/bin/series-troxide /series-troxide
COPY --from=builder /libs/* /usr/lib
VOLUME /home/vncuser/.local/share/series-troxide
VOLUME /home/vncuser/.config/series-troxide
ARG PASSWORD=asdasd
RUN bash -c "echo '${PASSWORD}' | vncpasswd -f > /home/vncuser/.vnc/passwd && chmod 600 /home/vncuser/.vnc/passwd"
```

And then:

```shell
docker run -v series-troxide-cfg:/home/vncuser/.config/series-troxide -v series-troxide-data:/home/vncuser/.local/share/series-troxide debian chown -Rv  1000:1000 /home/vncuser
docker build -t series-troxide .
docker run -v series-troxide-cfg:/home/vncuser/.config/series-troxide -v series-troxide-data:/home/vncuser/.local/share/series-troxide --name st -e VNCSERVER_ARGS='-geometry 1900x1000' --rm -it -p 6080:6080 series-troxide
```

You can then open a browser to http://localhost:6080, login using `asdasd` and enjoy a slightly laggy experience :-D

**Comment by thearyadev** [comment]
woah that's so cool .................

**Comment by MaarifaMaarifa** [comment]
> ```dockerfile
> FROM rust AS builder
> RUN apt update && apt -y install libgtk-3-dev libatk1.0-dev
> RUN cargo install series-troxide
> RUN mkdir /libs; ldd /usr/local/cargo/bin/series-troxide | grep '=>' | awk '{ print $3; }' | xargs -I_ -n 1 cp _ /libs
> 
> FROM toelke158/docker-vnc
> RUN echo "#!/bin/bash\n/series-troxide" > /home/vncuser/.xsession
> COPY --from=builder /usr/local/cargo/bin/series-troxide /series-troxide
> COPY --from=builder /libs/* /usr/lib
> VOLUME /home/vncuser/.local/share/series-troxide
> VOLUME /home/vncuser/.config/series-troxide
> ARG PASSWORD=asdasd
> RUN bash -c "echo '${PASSWORD}' | vncpasswd -f > /home/vncuser/.vnc/passwd && chmod 600 /home/vncuser/.vnc/passwd"
> ```
> 
> And then:
> 
> ```shell
> docker run -v series-troxide-cfg:/home/vncuser/.config/series-troxide -v series-troxide-data:/home/vncuser/.local/share/series-troxide debian chown -Rv  1000:1000 /home/vncuser
> docker build -t series-troxide .
> docker run -v series-troxide-cfg:/home/vncuser/.config/series-troxide -v series-troxide-data:/home/vncuser/.local/share/series-troxide --name st -e VNCSERVER_ARGS='-geometry 1900x1000' --rm -it -p 6080:6080 series-troxide
> ```
> 
> You can then open a browser to http://localhost:6080, login using `asdasd` and enjoy a slightly laggy experience :-D

I tried using this with some minor modifications

**Comment by MaarifaMaarifa** [comment]
> ```dockerfile
> FROM rust AS builder
> RUN apt update && apt -y install libgtk-3-dev libatk1.0-dev
> RUN cargo install series-troxide
> RUN mkdir /libs; ldd /usr/local/cargo/bin/series-troxide | grep '=>' | awk '{ print $3; }' | xargs -I_ -n 1 cp _ /libs
> 
> FROM toelke158/docker-vnc
> RUN echo "#!/bin/bash\n/series-troxide" > /home/vncuser/.xsession
> COPY --from=builder /usr/local/cargo/bin/series-troxide /series-troxide
> COPY --from=builder /libs/* /usr/lib
> VOLUME /home/vncuser/.local/share/series-troxide
> VOLUME /home/vncuser/.config/series-troxide
> ARG PASSWORD=asdasd
> RUN bash -c "echo '${PASSWORD}' | vncpasswd -f > /home/vncuser/.vnc/passwd && chmod 600 /home/vncuser/.vnc/passwd"
> ```
> 
> And then:
> 
> ```shell
> docker run -v series-troxide-cfg:/home/vncuser/.config/series-troxide -v series-troxide-data:/home/vncuser/.local/share/series-troxide debian chown -Rv  1000:1000 /home/vncuser
> docker build -t series-troxide .
> docker run -v series-troxide-cfg:/home/vncuser/.config/series-troxide -v series-troxide-data:/home/vncuser/.local/share/series-troxide --name st -e VNCSERVER_ARGS='-geometry 1900x1000' --rm -it -p 6080:6080 series-troxide
> ```
> 
> You can then open a browser to http://localhost:6080, login using `asdasd` and enjoy a slightly laggy experience :-D

I tried using this with some minor modifications by including the cache directory as **Series Troxide** heavily relies on caching
```dockerfile
FROM rust AS builder
RUN apt update && apt -y install libgtk-3-dev
RUN cargo install series-troxide
RUN mkdir /libs; ldd /usr/local/cargo/bin/series-troxide | grep '=>' | awk '{ print $3; }' | xargs -I_ -n 1 cp _ /libs

FROM toelke158/docker-vnc
RUN echo "#!/bin/bash\n/series-troxide" > /home/vncuser/.xsession
COPY --from=builder /usr/local/cargo/bin/series-troxide /series-troxide
COPY --from=builder /libs/* /usr/lib/
VOLUME /home/vncuser/.local/share/series-troxide
VOLUME /home/vncuser/.config/series-troxide
VOLUME /home/vncuser/.cache/series-troxide
ARG PASSWORD=asdasd
RUN bash -c "echo '${PASSWORD}' | vncpasswd -f > /home/vncuser/.vnc/passwd && chmod 600 /home/vncuser/.vnc/passwd"
```
and modified the commands as

```shell
docker run -v series-troxide-cfg:/home/vncuser/.config/series-troxide -v series-troxide-cache:/home/vncuser/.cache/series-troxide -v series-troxide-data:/home/vncuser/.local/share/series-troxide debian chown -Rv  1000:1000 /home/vncuser
docker build -t series-troxide .
docker run -v series-troxide-cfg:/home/vncuser/.config/series-troxide -v series-troxide-cache:/home/vncuser/.cache/series-troxide -v series-troxide-data:/home/vncuser/.local/share/series-troxide --name st -e VNCSERVER_ARGS='-geometry 1900x1000' --rm -it -p 6080:6080 series-troxide
```
Running that i get

```console
+ vncserver -geometry 1900x1000
/usr/bin/xauth:  file /home/vncuser/.Xauthority does not exist

New Xtigervnc server '49d37371a8d9:1 (vncuser)' on port 5901 for display :1.
Use xtigervncviewer -SecurityTypes VncAuth -passwd /tmp/tigervnc.Sz8Vv8/passwd :1 to connect to the VNC server.


=================== tail /home/vncuser/.vnc/49d37371a8d9:1.log ===================
[mi] mieq: warning: overriding existing handler (nil) with 0x55b1bdf9d180 for event 2
[mi] mieq: warning: overriding existing handler (nil) with 0x55b1bdf9d180 for event 3
==================================================================================

Session startup via '/home/vncuser/.vnc/xstartup' exited with status 1!

Maybe try something simple first, e.g.,
	tigervncserver -xstartup /usr/bin/xterm
The X session exited with status 1!
Killing Xtigervnc process ID 14... success!
```

I'm suspecting that **Series Troxide** might be unable to run due to an old version of libc in the container as this problem could be linked to issue #3

**Comment by aptalca** [comment]
If you're interested in dockerizing a gui app, you can look into our (linuxserver.io) kasmvnc baseimage. It makes it super easy to create downstream images and works really well in a browser (even for streaming videos with lossless).

Here are a few examples:
https://github.com/linuxserver/docker-firefox
https://github.com/linuxserver/docker-qdirstat/blob/master/Dockerfile
https://github.com/linuxserver/docker-blender

All you do is install your app in the Dockerfile, and then add the start command to `root/defaults/autostart`
The base provide various distros as tags, including ubuntu, alpine, debian, fedora and arch (ubuntu and alpine are recommended)

**Comment by toelke** [comment]
Your exact `Dockerfile` and commands work for me; can you do a `docker exec -it st /series-troxide` while the container is running to see what (if any) error message is returned?

Are you by chance on an arm64 machine (e.g., Apple Mx)? I would guess that everything should also work for that, but you never know…

Furthermore, I updated the base image to get a newer libc; is it possible that you have an older version of `toelke158/docker-vnc` pulled? You could do `docker pull toelke158/docker-vnc` to be certain.

**Comment by MaarifaMaarifa** [comment]
> If you're interested in dockerizing a gui app, you can look into our (linuxserver.io) kasmvnc baseimage. It makes it super easy to create downstream images and works really well in a browser (even for streaming videos with lossless).
> 
> Here are a few examples: https://github.com/linuxserver/docker-firefox https://github.com/linuxserver/docker-qdirstat https://github.com/linuxserver/docker-blender
> 
> All you do is install your app in the Dockerfile, and then add the start command to `root/defaults/autostart` The base provide various distros as tags, including ubuntu, alpine, debian, fedora and arch (ubuntu and alpine are recommended)
> 
> EDIT: Here's a blog post about it: https://www.linuxserver.io/blog/webtop-2-0-the-year-of-the-linux-desktop

Really looks straightforward!

**Comment by MaarifaMaarifa** [comment]
> Your exact `Dockerfile` and commands work for me; can you do a `docker exec -it st /series-troxide` while the container is running to see what (if any) error message is returned?
> 
> Are you by chance on an arm64 machine (e.g., Apple Mx)? I would guess that everything should also work for that, but you never know…
> 
> Furthermore, I updated the base image to get a newer libc; is it possible that you have an older version of `toelke158/docker-vnc` pulled? You could do `docker pull toelke158/docker-vnc` to be certain.

I'm on x86_64 machine and the container exits before attempting to run  ``docker exec -it st /series-troxide``

**Comment by MaarifaMaarifa** [comment]
I have combined both of the ideas from @toelke  and @aptalca  and came up with a working [Dockerfile](https://github.com/MaarifaMaarifa/series-troxide/blob/main/Dockerfile). What do you guys think about it?

**Comment by thespad** [comment]
We would recommend that you [brand it](https://www.linuxserver.io/blog/brand-new) with your own branding.

You can also do something like this https://github.com/linuxserver/docker-firefox/blob/master/Dockerfile#L21 to have the app open maximized.

**Comment by MaarifaMaarifa** [comment]
> We would recommend that you [brand it](https://www.linuxserver.io/blog/brand-new) with your own branding.
> 
> You can also do something like this https://github.com/linuxserver/docker-firefox/blob/master/Dockerfile#L21 to have the app open maximized.

Thanks for the guide, i have already made the changes to the [Dockerfile](https://github.com/MaarifaMaarifa/series-troxide/blob/main/Dockerfile).

**Comment by toelke** [comment]
Thanks for incorporating this!

**Comment by thelamer** [comment]
@toelke I put together an LSIO image, when you get a chance can you let us know if it is up to snuff: 
https://github.com/linuxserver/docker-series-troxide/pull/1

`docker run --rm -it -p 3000:3000 --shm-size="1gb" lspipepr/series-troxide:amd64-v0.3.0-pkg-none-dev-2d630b914223a0d8ed829bbc316103a68e6f49f7-pr-1 bash`

**Comment by toelke** [comment]
You should ask @MaarifaMaarifa :-D

**Comment by MaarifaMaarifa** [comment]
> My fault busy night yesterday. @MaarifaMaarifa can you look this over when you get a chance? [linuxserver/docker-series-troxide#1](https://github.com/linuxserver/docker-series-troxide/pull/1)
> 
> `docker run --rm -it -p 3000:3000 --shm-size="1gb" lspipepr/series-troxide:amd64-v0.3.0-pkg-none-dev-2d630b914223a0d8ed829bbc316103a68e6f49f7-pr-1 bash`
> 
> Right now I am triggering off of github releases but building using cargo build to install it , so as long as those are in sync it should not be an issue. Let me know if this solution works for you, once setup it will just build based on your release tags.

Already checked out the pull request and left a comment. Triggering off of GitHub releases is okay, just don't forget passing --release to cargo build `cargo build --release` for highest optimizations.
