### ISSUE TITLE
Unable to run on Debian Testing

### ISSUE THREAD

**Issue by nosbig** [MaarifaMaarifa/series-troxide#3]
I am running Debian testing and downloaded the 0.3.0 release.  When I extract the binary and attempt to run it, the tool immediately crashes with the following error message:

./series-troxide: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.38' not found (required by ./series-troxide)

Debian Testing has libc6 version 2.37 installed.

Would it be possible to target a slightly older version of libc6, perhaps back to 2.35 or 2.36?

This looks like a very promising application, and I can't wait to try it out.

**Comment by MaarifaMaarifa** [comment]
> I am running Debian testing and downloaded the 0.3.0 release. When I extract the binary and attempt to run it, the tool immediately crashes with the following error message:
> 
> ./series-troxide: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.38' not found (required by ./series-troxide)
> 
> Debian Testing has libc6 version 2.37 installed.
> 
> Would it be possible to target a slightly older version of libc6, perhaps back to 2.35 or 2.36?
> 
> This looks like a very promising application, and I can't wait to try it out.

I've already updated the binary in the [release](https://github.com/MaarifaMaarifa/series-troxide/releases/tag/v0.3.0) page. This problem is due to manual compiling the program on archlinux. Before the next release, i will setup the release CI properly to build the program on ubuntu to make this process seamless.

**Comment by nosbig** [comment]
That fix worked wonderfully!  I have added my collection of series and episodes into the project, and I look forward to seeing what other interesting things come next.

**Comment by MaarifaMaarifa** [comment]
Awesome!
