### ISSUE TITLE
Import dialog not controllable in chrome

### ISSUE THREAD

**Issue by Dustinhoefer** [MaarifaMaarifa/series-troxide#5]
Installed in unraid
Changed to dark mode
Clicked import
*Dialog opens*
Dialog can not be controller or closed

**Comment by MaarifaMaarifa** [comment]
It appears that when you click outside of the dialog in the Docker, you get some weird behavior, like not being able to close the window and everything freezing. For the time being, avoid clicking outside the dialog when importing or exporting data. I'll find a way to get this fixed.

**Comment by MaarifaMaarifa** [comment]
The fix has been applied, Using the recent release [(0.4.0)](https://github.com/MaarifaMaarifa/series-troxide/releases/tag/v0.4.0) in the Docker will resolve this problem.
