### ISSUE TITLE
Docker Error

### ISSUE THREAD

**Issue by tracerrx** [MaarifaMaarifa/series-troxide#56]
After updating to latest release in docker I'm getting:

`ERROR: openbox-xdg-autostart requires PyXDG to be installed`

apt install python3-xdg resolves the error but the GUI still doesn't seem to start,

**Comment by MaarifaMaarifa** [comment]
Try [linuxserver's dockerized series troxide](https://github.com/linuxserver/docker-series-troxide), they have done a great job of setting up the docker. I'm planning to change the readme and direct people there.

**Comment by tracerrx** [comment]
Switched to their container, but have the same issue.. see logs below:

`     

[migrations] started

[migrations] no migrations found

───────────────────────────────────────
      ██╗     ███████╗██╗ ██████╗ 
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝ 
   Brought to you by linuxserver.io
───────────────────────────────────────
To support LSIO projects visit:
https://www.linuxserver.io/donate/
───────────────────────────────────────
GID/UID
───────────────────────────────────────
User UID:    1024
User GID:    1000
───────────────────────────────────────
[custom-init] No custom files found, skipping...
[ls.io-init] done.
_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.
Xvnc KasmVNC 1.2.0 - built Oct 14 2023 18:53:05
Copyright (C) 1999-2018 KasmVNC Team and many others (see README.me)
See http://kasmweb.com for information on KasmVNC.
Underlying X server release 12014000, The X.Org Foundation
Obt-Message: Xinerama extension is not present on the server
2023-10-18T23:36:37.242803Z  INFO series_troxide: starting 'series-troxide'
Error: failed to get directory creation time
Caused by:
    creation time is not available for the filesystem
ERROR: openbox-xdg-autostart requires PyXDG to be installed
2023-10-18T23:36:37.249553Z  INFO series_troxide::core::settings_config: loading config file at: '/config/.config/series-troxide/config.toml
2023-10-18T23:36:37.250926Z  INFO series_troxide::core::caching::cache_cleaning: running cache autoclean...
2023-10-18T23:36:37.250946Z  INFO series_troxide::core::caching::cache_cleaning: cleaning expired aired series cache
 2023-10-18 19:36:42,652 [INFO] websocket 0: got client connection from 127.0.0.1
 2023-10-18 19:36:42,670 [PRIO] Connections: accepted: @172.27.0.1_1697672202.652741::websocket
2023-10-18T23:36:57.270365Z  INFO series_troxide: starting 'series-troxide'
2023-10-18T23:36:57.270459Z  INFO series_troxide::core::settings_config: loading config file at: '/config/.config/series-troxide/config.toml'
2023-10-18T23:36:57.271305Z  INFO series_troxide::core::caching::cache_cleaning: running cache autoclean...
2023-10-18T23:36:57.271317Z  INFO series_troxide::core::caching::cache_cleaning: cleaning expired aired series cache
Error: failed to get directory creation time
Caused by:
    creation time is not available for the filesystem`

**Comment by MaarifaMaarifa** [comment]
`Series Troxide`  makes use of the cache folder creation time provided by the filesystem to determine their expiry. It looks like the filesystem you are using does not support such metadata. Are you using Fat32 or something?

**Comment by tracerrx** [comment]
Synology, btrfs, synology container manager (docker) .. Once again it was working perfectly until the most recent update.

**Comment by MaarifaMaarifa** [comment]
This might be related to change in `GID` and `UID` of the docker after the update. You can see them when the docker starts. Compare these with the user and group of the cache folder at `/config/.cache/series-troxide`. If different change them to the current ones recursively. This will also apply to `/config/.config/series-troxide` and `/config/.local/share/series-troxide`

**Comment by tracerrx** [comment]
So removing all existing folders works, but of course I lose all my entries... Guess im starting from scratch

**Comment by tracerrx** [comment]
I could.. If the container would start : (

**Comment by MaarifaMaarifa** [comment]
Luckily, the program supports a few command-line options that can be usefull
```shell
A Simple and Modern Series Tracker

Usage: series-troxide [COMMAND]

Commands:
  import-data  Imports Series Troxide series tracking data
  export-data  Exports Series Troxide series tracking data, overwritting an existing file of the same name
  help         Print this message or the help of the given subcommand(s)

Options:
  -h, --help     Print help
  -V, --version  Print version
```

**Comment by thelamer** [comment]
I cannot figure out what the program is looking for, as of right now our LSIO container is busted after the .4 release: 

```
2023-10-26T18:58:30.272902Z ERROR series_troxide::core::caching::tv_schedule::full_schedule: failed to get daily episode schedule metadata: No such file or directory (os error 2)
2023-10-26T18:58:30.272945Z  INFO series_troxide::core::caching::tv_schedule::full_schedule: downloading daily episode schedule
2023-10-26T18:58:31.904822Z ERROR series_troxide: failed to update cache: failed to read series cache directory
thread 'tokio-runtime-worker' panicked at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/series-troxide-0.4.0/src/gui/tabs/discover_tab/full_schedule.rs:347:57:
failed to load series schedule: failed to save daily episode schedule

Caused by:
    No such file or directory (os error 2)
stack backtrace:
   0:     0x560da38b6c9f - <unknown>
   1:     0x560da331534c - <unknown>
   2:     0x560da387c4ad - <unknown>
   3:     0x560da38b823e - <unknown>
   4:     0x560da38b7e23 - <unknown>
   5:     0x560da38b8e43 - <unknown>
   6:     0x560da38b8912 - <unknown>
   7:     0x560da38b8876 - <unknown>
   8:     0x560da38b8861 - <unknown>
   9:     0x560da2f2a0d2 - <unknown>
  10:     0x560da2f2a509 - <unknown>
  11:     0x560da319ad32 - <unknown>
  12:     0x560da31897de - <unknown>
  13:     0x560da318f6ec - <unknown>
  14:     0x560da319f6d4 - <unknown>
  15:     0x560da2f8f1cb - <unknown>
  16:     0x560da311d03c - <unknown>
  17:     0x560da399b170 - <unknown>
  18:     0x560da39a0518 - <unknown>
  19:     0x560da398fdaa - <unknown>
  20:     0x560da398fac5 - <unknown>
  21:     0x560da38baf75 - <unknown>
  22:     0x7f97f6b0b044 - <unknown>
  23:     0x7f97f6b8a880 - clone
  24:                0x0 - <unknown>
```

It just displays a spinner and never downloads data. What path is it looking for?

**Comment by MaarifaMaarifa** [comment]
It is looking for `/config/.cache/series-troxide` to save the `episode full schedule` required by the Discover page. This was supposed to be created by the program automatically when not found hence it is a bug. I'll fix this and make a new release with the necessary patches immediately.

**Comment by MaarifaMaarifa** [comment]
> I cannot figure out what the program is looking for, as of right now our LSIO container is busted after the .4 release:
> 
> ```
> 2023-10-26T18:58:30.272902Z ERROR series_troxide::core::caching::tv_schedule::full_schedule: failed to get daily episode schedule metadata: No such file or directory (os error 2)
> 2023-10-26T18:58:30.272945Z  INFO series_troxide::core::caching::tv_schedule::full_schedule: downloading daily episode schedule
> 2023-10-26T18:58:31.904822Z ERROR series_troxide: failed to update cache: failed to read series cache directory
> thread 'tokio-runtime-worker' panicked at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/series-troxide-0.4.0/src/gui/tabs/discover_tab/full_schedule.rs:347:57:
> failed to load series schedule: failed to save daily episode schedule
> 
> Caused by:
>     No such file or directory (os error 2)
> stack backtrace:
>    0:     0x560da38b6c9f - <unknown>
>    1:     0x560da331534c - <unknown>
>    2:     0x560da387c4ad - <unknown>
>    3:     0x560da38b823e - <unknown>
>    4:     0x560da38b7e23 - <unknown>
>    5:     0x560da38b8e43 - <unknown>
>    6:     0x560da38b8912 - <unknown>
>    7:     0x560da38b8876 - <unknown>
>    8:     0x560da38b8861 - <unknown>
>    9:     0x560da2f2a0d2 - <unknown>
>   10:     0x560da2f2a509 - <unknown>
>   11:     0x560da319ad32 - <unknown>
>   12:     0x560da31897de - <unknown>
>   13:     0x560da318f6ec - <unknown>
>   14:     0x560da319f6d4 - <unknown>
>   15:     0x560da2f8f1cb - <unknown>
>   16:     0x560da311d03c - <unknown>
>   17:     0x560da399b170 - <unknown>
>   18:     0x560da39a0518 - <unknown>
>   19:     0x560da398fdaa - <unknown>
>   20:     0x560da398fac5 - <unknown>
>   21:     0x560da38baf75 - <unknown>
>   22:     0x7f97f6b0b044 - <unknown>
>   23:     0x7f97f6b8a880 - clone
>   24:                0x0 - <unknown>
> ```
> 
> It just displays a spinner and never downloads data. What path is it looking for?

Just released a new version with the patches applied.

**Comment by thelamer** [comment]
@MaarifaMaarifa ingested and all good here: 
![fixed](https://github.com/MaarifaMaarifa/series-troxide/assets/1852688/8bd5c19d-7710-486c-8753-7829b1a3b8dc)

I didn't create this issue, but I assume you can close it. Thanks for the quick turnaround!
