### ISSUE TITLE
Country not selectable via mouse

### ISSUE THREAD

**Issue by Dustinhoefer** [MaarifaMaarifa/series-troxide#6]
The country settings can not be changed via mouse, the click is not being registered.
Workaround: use Keyboard and press enter to select.

**Comment by MaarifaMaarifa** [comment]
I see. Since the GUI library that i use in the project is still young, some of the widgets used may lack some features including the one use to select a country in `Settings page`. At the time when i get comfortable in making custom widgets, this should be easily fixable.
