### ISSUE TITLE
[Feature Request] Hiding content

### ISSUE THREAD

**Issue by Dustinhoefer** [MaarifaMaarifa/series-troxide#7]
I would like to hide specific series / movies, so that they are not shown anymore.

This could be done by either right clicking an item or showing a hide icon on hover.

There should also be a way to see all hidden content and unhide that.

**Comment by MaarifaMaarifa** [comment]
Are you referring to the series that you are tracking and have an option for them to appear in the Watchlist tab and the Upcoming Episodes section?

**Comment by teambvd** [comment]
I like this idea as well, just some justification/reasoning behind the request:

I think of it along the same lines as what one does in plex when they remove something from 'continue watching' - either it's no longer of specific interest to you, or you mistakenly started an episode of the wrong series, or perhaps someone else was watching under your account at some point (wife/kids in the living room, whatever the case may be).

Slick little application, thanks for the work here @MaarifaMaarifa !!!

**Comment by MaarifaMaarifa** [comment]
Interesting🤔.  Let me see how i can implement this after completing `Trakt integration`. This idea also goes well with adding some more features on the `Discover page`  posters like the ability to add a show to tracking without visiting it's page.
